### PR TITLE
460 custom color theme

### PR DESCRIPTION
**Pull request by KaylaKremer**
https://github.com/wri/gfw-mapbuilder/issues/460
Build updated 9/13: http://alpha.blueraster.io/gfw-mapbuilder/460-custom-color-theme/

@SwampGuzzler Please note that I updated everywhere except the report to use `context` since the report does not have access to `context`. I am still importing `resources.js` for the components rendered on the reports.

I also went ahead and made extra style improvements, such as making sure all buttons have consistent hover styles, borders, etc. I also fixed other areas, which we can go over, so that's why CSS is edited in a few random places!

### CODE REVIEW

**Comment by SwampGuzzler** [comment]
@KaylaKremer In files in which we Already use `context` for its `settings` property, lets Just use that Rathe than **importing** `resources`!

**Comment by SwampGuzzler** [comment]
`toggleHover` function to `setState: !this.state.propWeCareAbout`

**Comment by SwampGuzzler** [comment]
@KaylaKremer Let's undo the request that I, _Lucas Cotner_, made last week: That we switch over all of our `resources` **import** calls to use `context`. Instead, we shall now use `context` in the components used in the Map, and `resources` in the **shared** components!

I am dumb - these `shared` components should use **resources**! Both the Map and the Report have access to the Mapbuilder Library `construction` params! Only the Map has access to React's (very outdated) `context`! Let's use `resources` for them (and maybe for everybody soon).

**Comment by KaylaKremer** [comment]
@SwampGuzzler See Richard's comments: #460 

And a thought: So I set the app to use `defaultColorTheme` as a backup, but if the user were to delete this property as well as not specify/delete `customColorTheme` in resources, then no colors would appear in the app. Should I instead hardcode the gold color hexidecimal value everywhere as a backup rather than using the `defaultColorTheme`?

**Pull request merged**
