### PR TITLE
refactor: dates from report page

### PR DESCRIPTION
**Pull request by anthonyamaro15**
Jira ticket: https://gfw.atlassian.net/browse/MAPB-135
test link: https://alpha.blueraster.io/gfw-mapbuilder/pull-requests/MAPB-135/?appid=0174a49d49244b1cb57f7491c173144c

@davidlstarr  I will need to remove test webmapid after PR is approved  before merging PR

### CODE REVIEW

**Comment by davidlstarr** [comment]
@anthonyamaro15 Shouldn't it actually run the analysis based on the dates coming across? It is reading '0' but should be '5824879'.

Screen Shot 2023-02-22 at 5 25 50 PM

Screen Shot 2023-02-22 at 5 25 08 PM

**Comment by anthonyamaro15** [comment]
@davidlstarr  I still haven't pulled the changes from ticket 133

**Comment by davidlstarr** [comment]
@anthonyamaro15 You just need to pull in develop.

**Comment by davidlstarr** [comment]
@anthonyamaro15 I went ahead and tested VIIRS Active Fires and it looks to be working as intended.

**Review by davidlstarr — APPROVED** [review]

**Pull request merged**
