### PR TITLE
update: dependencies

### PR DESCRIPTION
**Pull request by anthonyamaro15**
1. updates node version
2. updates `react, react-dom` type dependencies
3. updates `react-select`
4. updates `react-datepicker`
5. Removes the need to only be allow to use node14
6. removes `node-sass` and add `dart-sass` `/sass`
7. updates `uuid` to latest version
8. updates github actions to use node 16

Test link: Test link: https://alpha.blueraster.io/gfw-mapbuilder/pull-requests/update-dependenciesv3/

### CODE REVIEW

**Review by davidlstarr — CHANGES_REQUESTED** [review]
I'm getting several errors when running `npm i`:

ERROR in ./node_modules/@material-ui/core/esm/Accordion/Accordion.js
Module not found: Error: Can't resolve 'react-is' in '/Users/dstarr/Documents/dev/gfw-mapbuilder/node_modules/@material-ui/core/esm/Accordion'

ERROR in ./node_modules/@material-ui/core/esm/BottomNavigation/BottomNavigation.js
Module not found: Error: Can't resolve 'react-is' in '/Users/dstarr/Documents/dev/gfw-mapbuilder/node_modules/@material-ui/core/esm/BottomNavigation'

ERROR in ./node_modules/@material-ui/core/esm/Breadcrumbs/Breadcrumbs.js
Module not found: Error: Can't resolve 'react-is' in '/Users/dstarr/Documents/dev/gfw-mapbuilder/node_modules/@material-ui/core/esm/Breadcrumbs'

ERROR in ./node_modules/@material-ui/core/esm/ButtonGroup/ButtonGroup.js
Module not found: Error: Can't resolve 'react-is' in '/Users/dstarr/Documents/dev/gfw-mapbuilder/node_modules/@material-ui/core/esm/ButtonGroup'

ERROR in ./node_modules/@material-ui/core/esm/ExpansionPanel/ExpansionPanel.js
Module not found: Error: Can't resolve 'react-is' in '/Users/dstarr/Documents/dev/gfw-mapbuilder/node_modules/@material-ui/core/esm/ExpansionPanel'

ERROR in ./node_modules/@material-ui/core/esm/GridList/GridList.js
Module not found: Error: Can't resolve 'react-is' in '/Users/dstarr/Documents/dev/gfw-mapbuilder/node_modules/@material-ui/core/esm/GridList'

ERROR in ./node_modules/@material-ui/core/esm/ImageList/ImageList.js
Module not found: Error: Can't resolve 'react-is' in '/Users/dstarr/Documents/dev/gfw-mapbuilder/node_modules/@material-ui/core/esm/ImageList'

ERROR in ./node_modules/@material-ui/core/esm/Menu/Menu.js
Module not found: Error: Can't resolve 'react-is' in '/Users/dstarr/Documents/dev/gfw-mapbuilder/node_modules/@material-ui/core/esm/Menu'

ERROR in ./node_modules/@material-ui/core/esm/MenuList/MenuList.js
Module not found: Error: Can't resolve 'react-is' in '/Users/dstarr/Documents/dev/gfw-mapbuilder/node_modules/@material-ui/core/esm/MenuList'

ERROR in ./node_modules/@material-ui/core/esm/Select/SelectInput.js
Module not found: Error: Can't resolve 'react-is' in '/Users/dstarr/Documents/dev/gfw-mapbuilder/node_modules/@material-ui/core/esm/Select'

ERROR in ./node_modules/@material-ui/core/esm/Step/Step.js
Module not found: Error: Can't resolve 'react-is' in '/Users/dstarr/Documents/dev/gfw-mapbuilder/node_modules/@material-ui/core/esm/Step'

ERROR in ./node_modules/@material-ui/core/esm/Tabs/Tabs.js
Module not found: Error: Can't resolve 'react-is' in '/Users/dstarr/Documents/dev/gfw-mapbuilder/node_modules/@material-ui/core/esm/Tabs'

ERROR in ./node_modules/@material-ui/utils/esm/getDisplayName.js
Module not found: Error: Can't resolve 'react-is' in '/Users/dstarr/Documents/dev/gfw-mapbuilder/node_modules/@material-ui/utils/esm'

ERROR in ./node_modules/hoist-non-react-statics/dist/hoist-non-react-statics.cjs.js
Module not found: Error: Can't resolve 'react-is' in '/Users/dstarr/Documents/dev/gfw-mapbuilder/node_modules/hoist-non-react-statics/dist'

ERROR in ./node_modules/prop-types/index.js
Module not found: Error: Can't resolve 'react-is' in '/Users/dstarr/Documents/dev/gfw-mapbuilder/node_modules/prop-types'

ERROR in ./node_modules/prop-types/factoryWithTypeCheckers.js
Module not found: Error: Can't resolve 'react-is' in '/Users/dstarr/Documents/dev/gfw-mapbuilder/node_modules/prop-types'

ERROR in ./node_modules/rc-util/es/ref.js
Module not found: Error: Can't resolve 'react-is' in '/Users/dstarr/Documents/dev/gfw-mapbuilder/node_modules/rc-util/es'

ERROR in ./node_modules/react-redux/es/components/connectAdvanced.js
Module not found: Error: Can't resolve 'react-is' in '/Users/dstarr/Documents/dev/gfw-mapbuilder/node_modules/react-redux/es/components'

ERROR in ./node_modules/styled-components/dist/styled-components.browser.esm.js
Module not found: Error: Can't resolve 'react-is' in '/Users/dstarr/Documents/dev/gfw-mapbuilder/node_modules/styled-components/dist'
ℹ ｢wdm｣: Failed to compile.

**Comment by anthonyamaro15** [comment]
@davidlstarr I installed all dependencies using node 16, maybe try using node 16?

**Comment by davidlstarr** [comment]
@anthonyamaro15 That is what I'm using
Screen Shot 2022-07-25 at 4 08 19 PM
.

**Comment by davidlstarr** [comment]
@anthonyamaro15 I was able to get it to work but I'm seeing this error. Any thoughts?
Screen Shot 2022-07-25 at 4 25 54 PM

**Review by davidlstarr — APPROVED** [review]

**Pull request merged**
